import type { Metadata } from "next"
import { Barlow } from "@next/font/google"
import "./globals.css"
import { NextUIProvider } from "@nextui-org/react"

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "ChainLink Crypto Pulse",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-indigo-950">
      <body className={barlow.className}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  )
}

{
}
